name: publish

on: 
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Luajit
        run: |
          cd build
          .\make_win64_luajit.bat
      - name: UploadJit
        uses: actions/upload-artifact@v3
        with:
          path: ./build/build_lj64/Release/
          name: plugin_luajit
